name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker-react-app:$(date +%s)
      
    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'
      
    - name: Beanstalk Deploy
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        # AWS Access Key
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
        # AWS Secret Key
        aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
        # AWS Region
        region: ap-northeast-2
        # Beanstalk application name
        application_name: react-docker-app-v2
        # Beanstalk environment name. If empty a version will be created but not deployed anywhere.
        environment_name: React-docker-app-v2-env
        # Version label for new Beanstalk version
        version_label: ${{ github.sha }}

              
